### PR TITLE
Fix: Textual configuration does not work if heartBeat parameter is not explicitely defined (NullPointerException)

### PR DESCRIPTION
**Pull request by pfink**
...setting default to 360 as stated in description should fix it

### CODE REVIEW

**Comment by pfink** [comment]
Hi,
I think you're right, 60s fits better :) In this PR I just choosed 360 because it was stated in the description. Of course, the value in the description should match the default value.

**Comment by Wire82** [comment]
Okay. I guess then I can also remove the definition of an fixed value within the HeosDiscoveryParticipant.class where a value is assigned to the heart beat delay

**Comment by pfink** [comment]
Ok, but why did you merge now? I thought you'd make a seperate commit with the 60s value ;-)

**Comment by Wire82** [comment]
I committed your change an changed the value. :)

**Comment by pfink** [comment]
Oh, okay :D

**Comment by Wire82** [comment]
Okay. Done. :) Thank you again for supporting me.

**Pull request merged**
